# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - volodya-lombrozo
ec2:
  type: t2.2xlarge
docker:
  image: lombrozo/rultor-image-java:master
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
merge:
  script: mvn clean install -Pqulice --errors --batch-mode
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn flatten:flatten
    xcop --fix .flattened-pom.xml
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean install -Pqulice --errors --batch-mode
    mvn clean deploy -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
