# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: mvn
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
        java: [11, 23]
        exclude:
          - os: windows-2022
            java: 11
          - os: macos-15
            java: 11
    runs-on: ${{ matrix.os }}
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Detect Maven Path
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euo pipefail
          MVN="$(command -v mvn || true)"
          if [ -z "$MVN" ]; then
            echo "Maven not found on PATH"; exit 1
          fi
          echo "MAVEN_PATH=$MVN" >> "$GITHUB_ENV"
          echo "Detected Maven at: $MVN"
      - uses: JesseTG/rm@v1.0.3
        with:
          path: ~/.m2/repository/org/eolang
      - run: mvn clean install --errors --batch-mode
